name: Build and Push Docker Image with Tag
on: 
    push: 
        branches: [main]


jobs:
    build:
        runs-on: self-hosted
        steps:
        - name: checkout repo
          uses: actions/checkout@v3
          
        - name: set Image_tag
          run:  echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

        - name: Docker login (PowerShell-safe)
          run: |
            $token = "${{ secrets.DOCKER_PASSWORD }}"
            $username = "${{ secrets.DOCKER_USERNAME }}"
            $token | docker login -u $username --password-stdin
          shell: pwsh
          
        - name:  build docker image
          run: docker build -t abhishekkk15/swiggy_clone:${{env.IMAGE_TAG}}
        
        - name: push image to docker hub
          run: docker push abhishekkk15/swiggy_clone:${{env.IMAGE_TAG}}

        - name: update deployment yml with new tag
          run: |
                sed -i "s|image: abhishekkk15/swiggy_clone:.*|image: abhishekkk15/swiggy_clone:${{ env.IMAGE_TAG }}|" k8s/deployment.yaml

        - name: Commit and push updated YAML
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git commit -am "Update image tag to ${{ env.IMAGE_TAG }}"
            git push
