name: Build and Push Docker Image with Tag
on: 
    push: 
        branches: [main]


jobs:
    build:
        runs-on: self-hosted
        steps:
        - name: checkout repo
          uses: actions/checkout@v3
          
        - name: Set IMAGE_TAG (Windows PowerShell)
          run: |
            $dateTag = Get-Date -Format "yyyyMMddHHmmss"
            Add-Content -Path $env:GITHUB_ENV -Value "IMAGE_TAG=$dateTag"
          shell: powershell
        - name: Debug Docker credentials
          run: |
            echo "Username: ${{ secrets.DOCKER_USERNAME }}"
            echo "Token length: $(${env:DOCKER_PASSWORD}.Length)"
          shell: powershell


        - name: Docker login (PowerShell with full command)
          shell: powershell
          run: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"



          
        - name:  build docker image
          run: docker build -t abhishekkk15/swiggy_clone:${{env.IMAGE_TAG}} .
        
        - name: push image to docker hub
          run: docker push abhishekkk15/swiggy_clone:${{env.IMAGE_TAG}}

        - name: Update image tag in deployment.yml (PowerShell)
          shell: powershell
          run: |
            (Get-Content "k8s/deployment.yml") -replace "image: .*/swiggy_clone:.*", "image: abhishekkk15/swiggy_clone:${env:IMAGE_TAG}" | Set-Content "k8s/deployment.yml"

        - name: Commit and push updated YAML
          shell: powershell
          working-directory: "${{ github.workspace }}"
          env:
            GH_PAT: ${{ secrets.GH_PAT }}
          run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"

            git add k8s/deployment.yml
            git commit -m "Update image to $env:GITHUB_SHA"
            if ($LASTEXITCODE -ne 0) {
              Write-Output "No changes to commit"
            }

            Write-Output "Using token: $($env:GH_PAT.Substring(0, 4))********"

            git push -f https://x-access-token:$env:GH_PAT@github.com/abhishekkkk-15/Swiggy_FrontPage_Clone.git main







